name: Jargon
current_version:
    number: 0.1.1
    info: >
        Initial version + bug fixes
description: >
    If I can just overclock the Unix Django, I can BASIC the DDOS root,. Damn. But wait... If I can disencrypt their kilobytes with a backdoor handshake then... JACKPOT!
files:
- plugins/jargon/
- plugins/jargon/__init__.py
- plugins/jargon.plug
- config/plugins/jargon.yml.example
requires:
    modules: []
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Jargon/README.md
