name: DrunkOctopus
current_version:
    number: 0.2.1
    info: >
        * Fixed mistake where drunkenness wasn't fully utilised
description: >
    Gives your squidopus shots of vodka and rum.
files:
- plugins/drunkoctopus/
- plugins/drunkoctopus/__init__.py
- plugins/drunkoctopus.plug
- config/plugins/drunkoctopus.yml.example
requires:
    modules: []
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/DrunkOctopus/README.md
