name: URL Tools
current_version:
    number: 0.2.1
    info: >
        Make plugin reload-friendly
description: >
    Provides a set of tools for working with the URLs plugin. These tools provide both URL shorteners
    and specific domain handlers for the URL title parser.

    == DONE ==
    Shorteners: is.gd,  nazr.in, v.gd, waa.ai
    Sites: youtube.com, osu.ppy.sh, github.com

files:
- plugins/urltools.plug
- plugins/urltools/
- plugins/urltools/__init__.py
- config/plugins/urltools.yml.example
requires:
    modules:
    - requests
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/URL-tools/README.md
