name: Triggers
current_version:
    number: 0.4.0
    info: >
        + Additional response types (channel/global kick/ban)
description: >
    Configurable trigger responses
files:
- plugins/triggers/
- plugins/triggers/__init__.py
- plugins/triggers.plug
- config/plugins/triggers.yml.example
requires:
    modules: []
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Triggers/README.md
