name: Old-plugins
current_version:
    number: 0.0.6
    info: >
        Updated for new command handler signature
description: >
    Rewritten versions of most of the old plugins from the original Ultros.

    So far, the following plugins have been ported:
    - Ass: weird-ass bucket => weird ass-bucket
    - Brainfuck: A simple brainfuck interpreter
    - GeoIP: A simple (but kind-of-accurate) GeoIP lookup plugin using freegeoip.net
    - Items: The classic give/get plugin
    - Lastseen: When were you last on?
    - Russian-roulette: Bang!
files:
- plugins/ass/
- plugins/brainfuck/
- plugins/geoip/
- plugins/items/
- plugins/lastseen/
- plugins/russianroulette/
- config/plugins/brainfuck.yml.example
- config/plugins/items.yml.example
- plugins/ass/__init__.py
- plugins/ass.plug
- plugins/brainfuck/__init__.py
- plugins/brainfuck.plug
- plugins/geoip/__init__.py
- plugins/geoip.plug
- plugins/items/__init__.py
- plugins/items.plug
- plugins/lastseen/__init__.py
- plugins/lastseen.plug
- plugins/russianroulette/__init__.py
- plugins/russianroulette.plug
requires:
    modules: []
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Old-plugins/README.md
