name: Currency conversion
current_version:
    number: 0.0.2
    info: >
        Updated for new command handler signature
description: >
    Provides a command to convert between currencies.
files:
- plugins/money.plug
- plugins/money/
- plugins/money/__init__.py
- config/plugins/money.yml.example
requires:
    modules: []
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Money/README.md
