name: Wordnik
current_version:
    number: 0.0.1
    info: >
        Initial version. Dict and WOTD commands are done.
description: >
    Provides a dictionary lookup tool using the Wordnik API and Wiktionary.

    [dict command] Look up the definition of a word.
    [wotd command] Look up the current word of the day and its definition.

    Both commands use Wiktionary for definitions, gracegully provided by the Wordnik API.
files:
- plugins/wordnik/
- plugins/wordnik.plug
- plugins/wordnik/__init__.py
- config/plugins/wordnik.example.yml
requires:
    modules:
    - "wordnik"
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Wordnik/README.md
