name: w3validator
current_version:
    number: 0.0.1
    info: >
        Initial release of the validator plugin.
description: >
    This plugin sends a request to validator.w3.org and reads it's headers, returning if the document was valid or not.
    You can validate multiple websites at once, up to three.
    Syntax: validate [url] [...]
# Plugin
files:
- plugins/w3validator.plug
- plugins/w3validator/
- plugins/w3validator/__init__.py
requires:
    modules: ["requests"]
    packages: []
documentation: https://github.com/UltrosBot/Ultros-contrib/blob/master/w3validator/README.md