name: Domai.nr
current_version:
    number: 0.3.0
    info: >
        Updated to new API.
description: >
    Domainr API integration. Current features:
    - Search
    - Info
files:
- plugins/domainr/
- plugins/domainr/__init__.py
- plugins/domainr.plug
- config/plugins/domainr.yml.example
requires:
    modules: [
        txrequests
    ]
    packages: []
documentation: https://github.com/UltrosBot/Ultros-contrib/blob/master/Domai.nr/README.md
