name: Domai.nr
current_version:
    number: 0.2.0
    info: >
        Added permission nodes to determine command output location.
description: >
    Domai.nr API integration. Current features:
    - Search
    - Info
files:
- plugins/domainr/
- plugins/domainr/__init__.py
- plugins/domainr.plug
requires:
    modules: [
        treq
    ]
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Domai.nr/README.md
