name: Domai.nr
current_version:
    number: "DELETED"
    info: >
        EOL plugin
description: >
    Domainr API integration. Current features:
    - Search
    - Info
files:
- plugins/domainr/
- plugins/domainr/__init__.py
- plugins/domainr.plug
- plugins/domainr/README.md
dont_skip:
- plugins/domainr/README.md
requires:
    modules: [
        treq
    ]
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Domai.nr/README.md
