name: Google
current_version:
    number: 0.1.0
    info: >
        Update for new URLs plugin and txrequests
description: >
    Allows you to do quick Google searches that return up to four results at a time.
files:
- config/plugins/google.yml.example
- plugins/google/
- plugins/google/__init__.py
- plugins/google/search.py
- plugins/google.plug
requires:
    modules:
    - txrequests
    packages: []
documentation: https://github.com/UltrosBot/Ultros-contrib/blob/master/Google/README.md
