name: Minecraft
current_version:
    number: 0.0.3
    info: >
        Query now uses Dinnerbone's mcstatus library from pip, and supports SRV records.
        The syntax of the mcquery command has changed - specify the port as part of the
        address where required.
description: >
    Provides a command for checking the status of a Minecraft server and a Minecraft/Mojang
    server status watcher.
files:
# Configuration
- config/plugins/minecraft.yml.example
# Plugin
- plugins/minecraft.plug
- plugins/minecraft/
- plugins/minecraft/__init__.py
- plugins/minecraft/minecraft_query.py
requires:
    modules:
    - "mcstatus"
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Minecraft/README.md
