name: Minecraft
current_version:
    number: 0.0.2
    info: >
        Added support for Textures and API.
description: >
    Provides a command for checking the status of a Minecraft server and a Minecraft/Mojang
    server status watcher.
files:
# Configuration
- config/plugins/minecraft.yml.example
# Plugin
- plugins/minecraft.plug
- plugins/minecraft/
- plugins/minecraft/__init__.py
- plugins/minecraft/minecraft_query.py
requires:
    modules: []
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Minecraft/README.md
