name: LastFM
current_version:
    number: 0.3.2
    info: >
        Fixed yet another edge-case in the LastFM API
description: >
    LastFM API integration. Current features:
    - Now Playing, including stats
    - Compare user tastes (Tasteometer)
files:
- plugins/lastfm/
- plugins/lastfm/__init__.py
- plugins/lastfm.plug
- config/plugins/lastfm.yml.example
requires:
    modules: [
        treq
    ]
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/LastFM/README.md
