name: LastFM
current_version:
    number: 0.2.2
    info: >
        Fix error with request exception handling
description: >
    LastFM API integration. Current features:
    - Now Playing, including stats
files:
- plugins/lastfm/
- plugins/lastfm/__init__.py
- plugins/lastfm.plug
- config/plugins/lastfm.yml.example
requires:
    modules: [
        treq
    ]
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/LastFM/README.md
