name: xkcd
current_version:
    number: 1.0.1
    info: >
        Fixed incorrect file path in package.
description: >
    xkcd comic searching
files:
- config/plugins/xkcd.yml
- plugins/xkcd/
- plugins/xkcd/__init__.py
- plugins/xkcd.plug
requires:
    modules: [
        treq
    ]
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/xkcd/README.md
