name: xkcd
current_version:
    number: 0.1.1
    info: >
        Updated for new command handler signature
description: >
    xkcd comic searching
files:
- plugins/xkcd/
- plugins/xkcd/__init__.py
- plugins/xkcd.plug
requires:
    modules: [
        requests
    ]
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/xkcd/README.md
