name: Web interface
current_version:
    number: 0.1.1
    info: >
        Add a couple API functions to allow adding headers and modifying the navbar.

        Also added automatic asset compilation and merging for .css and .js files.
        This requires a couple of additional modules, "webassets" and "cssmin". As
        usual, the package manager will install these for you.
description: >
    Provides a full web interface and REST API for Ultros.
     
    This includes management and manipulation, both via API keys and the standard authentication system.
    Currently, this is a HUGE work-in-progress. Expect big things, but don't expect them too soon!
     
    Requires both the "bottle", "mako" and "cherrypy" modules.
    If you're using the package manager, these will be installed for you, provided you have pip installed.
     
    Doesn't require any other packages, outside of the ones included with Ultros.
files:
# Configuration
- config/plugins/web.yml.example
# Plugin
- plugins/web.plug
- plugins/web/
- plugins/web/__init__.py
# Web files
- web/
- web/static/  # Yes, it's perfectly capable of serving whatever files you want
- web/static/custom.css
- web/templates/
- web/templates/base.html
- web/templates/index.html
- web/templates/navbar.html
requires:
    modules:
    - "bottle"
    - "cherrypy"
    - "cssmin"
    - "mako"
    - "webassets"
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Web/README.md
