name: Web interface
current_version:
    number: 0.1.4
    info: >
        Beginnings of the API and web interface.
description: >
    Provides a full web interface and REST API for Ultros.
     
    This includes management and manipulation, both via API keys and the standard authentication system.
    Currently, this is a HUGE work-in-progress. Expect big things, but don't expect them too soon!
     
    Requires both the "bottle", "mako" and "cherrypy" modules.
    If you're using the package manager, these will be installed for you, provided you have pip installed.
     
    Doesn't require any other packages, outside of the ones included with Ultros.
files:
# Configuration
- config/plugins/web.yml.example
# Plugin
- plugins/web.plug
- plugins/web/
- plugins/web/__init__.py
- plugins/web/admin.py
- plugins/web/api.py
- plugins/web/errors.py
- plugins/web/events.py
- plugins/web/yielder.py
# Web files
- web/
- web/static/  # Yes, it's perfectly capable of serving whatever files you want
- web/static/codemirror.css
- web/static/codemirror-compressed.js
- web/static/custom.css
- web/static/monokai.css
- web/templates/
- web/templates/admin/
- web/templates/base.html
- web/templates/generic.html
- web/templates/index.html
- web/templates/login.html
- web/templates/navbar.html
- web/templates/admin/file.html
requires:
    modules:
    - "beaker"
    - "bottle"
    - "cssmin"
    - "mako"
    - "webassets"
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Web/README.md
