name: Web interface
current_version:
    number: 1.0.1
    info: >
        Added support for OpenShift and binding to env vars
description: >
    Provides a full web interface and REST API for Ultros.
     
    This includes management and manipulation, both via API keys and the standard authentication system.
    Currently, this is a HUGE work-in-progress. Expect big things, but don't expect them too soon!
     
    Requires the "cyclone" and "mako" modules.
    If you're using the package manager, these will be installed for you.

    Doesn't require any other packages, outside of the ones included with Ultros.
files:
# Configuration
- config/plugins/web.yml.example
# Plugin - .plug file
- plugins/web.plug
# Plugin - folders
- plugins/web/
- plugins/web/routes/
- plugins/web/routes/account/
- plugins/web/routes/account/apikeys/
- plugins/web/routes/account/password/
- plugins/web/routes/account/users/
- plugins/web/routes/admin/
- plugins/web/routes/api/
- plugins/web/routes/api/admin/
# Plugin - files
- plugins/web/__init__.py
- plugins/web/apikeys.py
- plugins/web/decorators.py
- plugins/web/error_handler.py
- plugins/web/events.py
- plugins/web/request_handler.py
- plugins/web/sessions.py
- plugins/web/stats.py
- plugins/web/template_loader.py
- plugins/web/routes/__init__.py
- plugins/web/routes/index.py
- plugins/web/routes/login.py
- plugins/web/routes/login-reset.py
- plugins/web/routes/logout.py
- plugins/web/routes/account/__init__.py
- plugins/web/routes/account/index.py
- plugins/web/routes/account/apikeys/__init__.py
- plugins/web/routes/account/apikeys/create.py
- plugins/web/routes/account/apikeys/delete.py
- plugins/web/routes/account/password/__init__.py
- plugins/web/routes/account/password/change.py
- plugins/web/routes/account/users/__init__.py
- plugins/web/routes/account/users/logout.py
- plugins/web/routes/admin/__init__.py
- plugins/web/routes/admin/file.py
- plugins/web/routes/admin/files.py
- plugins/web/routes/admin/index.py
- plugins/web/routes/api/__init__.py
- plugins/web/routes/api/admin/__init__.py
- plugins/web/routes/api/admin/get_stats.py
# Assets - folders
- web/
- web/static/
- web/templates/
- web/templates/admin/
# Assets - files
- web/static/codemirror.css
- web/static/codemirror-compressed.js
- web/static/custom.css
- web/static/eclipse.css
- web/static/ultros.png
- web/static/ultros-logo.png
- web/templates/account.html
- web/templates/base.html
- web/templates/generic.html
- web/templates/index.html
- web/templates/login.html
- web/templates/login-reset.html
- web/templates/navbar.html
- web/templates/admin/file.html
- web/templates/admin/files.html
- web/templates/admin/index.html
requires:
    modules:
    - "cyclone"
    - "mako"
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Web/README.md
