name: Web interface
current_version:
    number: 0.1.0
    info: >
        Web classes are working, with a default index page and the ability to serve static files.
        This appears to be /FAST/, which is obviously a really good thing. More work needs done on it
          before we can have a proper JSON API, but it's getting there.
description: >
    Provides a full web interface and REST API for Ultros.
     
    This includes management and manipulation, both via API keys and the standard authentication system.
    Currently, this is a HUGE work-in-progress. Expect big things, but don't expect them too soon!
     
    Requires both the "bottle" and "cherrypy" modules. 
    If you're using the package manager, these will be installed for you, provided you have pip installed.
     
    Doesn't require any other packages, outside of the ones included with Ultros.
files:
# Configuration
- config/plugins/web.yml.example
# Plugin
- plugins/web.plug
- plugins/web/
- plugins/web/__init__.py
# Web files
- web/
- web/static/  # Yes, it's perfectly capable of serving whatever files you want
- web/static/custom.css
- web/templates/
- web/templates/base.html
- web/templates/index.html
- web/templates/navbar.html
requires:
    modules:
    - "bottle"
    - "cherrypy"
    - "mako"
    packages: []
documentation: https://github.com/McBlockitHelpbot/Ultros-contrib/blob/master/Web/README.md
